### ISSUE TITLE
KeyError: 'logfile'

### ISSUE THREAD

**Issue by srnlfk** [cinek810/snow-grafana-proxy#1]
# ./snow-grafana-proxy.py
Traceback (most recent call last):
  File "./snow-grafana-proxy.py", line 137, in <module>
    logging.basicConfig(filename=config['service']['logfile'],level=getattr(logging,config['service']['loglevel'].upper()))
  File "/usr/lib/python2.7/site-packages/backports/configparser/__init__.py", line 1279, in __getitem__
    raise KeyError(key)
KeyError: 'logfile'

**Comment by cinek810** [comment]
Thanks for that, looks like I've forgot to update the configuration template, check last commit.
